### ISSUE TITLE
Can we change the unicode vertical bar to ascii pipe?

### ISSUE THREAD

**Issue by ppi-agray** [meribold/timethis#1]
When our json loggers print the unicode character:
`log('│ ' * depth + f'{message}: {elapsed_time:.3f} seconds')`

It looks like this:
`{"message": "\u2502 bar: 1.003 seconds", "request_id": "093b08f728184f33a9dc8b434bafe4ac"}`

Can we change the unicode vertical bar character to an ascii pipe charcter?
`log('| ' * depth + f'{message}: {elapsed_time:.3f} seconds')`

Or have an option to pass in what delimiter we want?

I can create a PR for either case, or just fork the repo and use that.  Let me know which option (if any) you prefer and I'll be happy to do it.
Thanks!

**Comment by meribold** [comment]
Simply switching to an ASCII pipe seems like the best option to me.

**Comment by ppi-agray** [comment]
Great! I'll create a PR for you. Thanks!

**Comment by ppi-agray** [comment]
Oh! It looks like you beat me to the fix! THANKS!!! :)
